FROM python:3.12-slim

WORKDIR /app

COPY pipeline/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY pipeline/scrapy.cfg .
COPY pipeline/scraper ./scraper

CMD ["scrapy", "crawl", "publimaroc"]